name: drift_network_bridge
description: Middleware Network bridge support for drift
version: 0.0.1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  collection: ^1.16.0
  drift:
  postgres:
  meta: ^1.8.0
  json_serializable:
  stream_channel:
  uuid:
  typed_data:
  mqtt_client:
  async:
  archive:
  stack_trace:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.18.0
  melos:
  drift_testcases:
  json_annotation:
  build_runner:
  mockito:

dependency_overrides:
  drift_testcases:
    path: packages/drift/extras/integration_tests/drift_testcases

