name: drift_network_bridge
description: Middleware Network bridge support for drift
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  drift:
  postgres:
  meta: ^1.8.0
  json_serializable:
  stream_channel:
  uuid:
  typed_data:
  mqtt_client:
  async:
  archive:
  stack_trace:
  test_descriptor:
  rxdart:
  http:
  path:
  sqlite3:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.18.0
  drift_dev:
  melos:
  json_annotation:
  build_runner:
  mockito:
  analyzer:
  shelf:
